# Scenario definitions
# leap_id: LEAP internal ScenarioID integer

scenarios:
  Current Accounts:
    leap_id: 1
    description: Historical baseline / Mandatory in LEAP to fill in base year data
  Reference:
    leap_id: 2
    description: Reference projection from 9th edition (current policy extended)
  Target:
    leap_id: 3
    description: Policy target pathway from 9th edition ~partly~ implemented in early 10th edition exploration

# Default projection range
projection:
  start_year: 2022
  end_year: 2060
